apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: batch-orders-api
  namespace: batch-orders
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: batch-orders-api
  namespaceSelector:
    matchNames:
      - batch-orders
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
