apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-orders-api
  namespace: batch-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-orders-api
  template:
    metadata:
      labels:
        app: batch-orders-api
    spec:
      containers:
        - name: batch-orders-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "{{ .Values.env.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_NAME
              value: "{{ .Values.env.DB_NAME }}"
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
